mendersoftware/mender-api-gateway-docker

- nginx.conf
API /deployments/images endpoint has a specific configuration setup.
However, due to the location URL match not being specific enough,
requests going to /deployments/images/<id>, or
/deployments/images/<id>/download would still be caught by that rule and
routed to incorrect endpoint of deployments service.
@kjaskiewiczz @marekswiecznik @maciejmrowiec @mchalski
> nginx: more specific /api/integrations/0.1/deployments/images match

- nginx.conf
API routing for useradm service. Separate /auth/login endpoint for user
logins.
> nginx: setup routing for useradm service

- nginx.conf
Commit  50191fb643b7b3955f4338568034c3c2714364d5 should go along with https://github.com/mendersoftware/useradm/pull/8 as this will setup routing for token verification for all API endpoints, but we will hit a /token/verify stub implementation where all requests are accepted.
Additionally, the URI of incoming request is included in X-Original-URI header. This should allow us to verify and authorize requests.
commit 50191fb643b7b3955f4338568034c3c2714364d5
Author: Maciej Borzecki <maciej.borzecki@rndity.com>
Date:   Wed Nov 30 14:07:36 2016 +0100
nginx: setup request authorization for integrations API endpoints
Signed-off-by: Maciej Borzecki <maciej.borzecki@rndity.com>
commit 985ade0dc517b0d8858d652464473d66a30207dc
Author: Maciej Borzecki <maciej.borzecki@rndity.com>
Date:   Wed Nov 30 …
> userauth verify & enhancements

- nginx.conf
Intergrations API requests are routed through internal endpoint /userauth.
When a POST to /deployments/images hits this endpoint, the subrequset to
/useauth fails due to client_max_body_size check. This is hard to explain, as
the endpoint is configured to *drop* the body of original request. As a
workaround, allow body of any size, but keep the policy of removing it from a
forwarded auth request.
@mendersoftware/rndity @maciejmrowiec 
@pasinskim please verify this PR in your integration tests and report back the status.
> nginx: userauth: disable client_max_body_size check for /userauth

- nginx.conf
Disable buffering of image upload to a temporary file. This should prevent nginx
and client from reaching a timeout while waiting for deployments service to
upload the image to starge backend.
@mendersoftware/rndity @GregorioDiStefano @maciejmrowiec 
Edit: If you're running a compose setup on a single host and try to upload 10GB image, nginx is first to buffer the image, then deployments buffers the image, reaching 20GB at its peak. With this change we will end up with a single 10GB buffered file.
> nginx: image artifact upload

- nginx.conf
The rest of the system is lagging behind,
so the task cannot be completed at this time.
We need to revert once the `Create Tenant administrator` epic is
finished.
Signed-off-by: Marcin Pasinski <marcin.pasinski@cfengine.com>
> Reverting the change that enforced user auth for every API endpoint.

- nginx.conf
Setup listening on non SSL wrapped port to ease debugging. The port is not published by default, so unless someone explicitly publishes is to the outside world, it will remain inaccessible.
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
> nginx: enable listening on non SSL wrapped port

- nginx.conf
the change was tested manually by poking all services and their various APIs. for sure this was not a 100% check, but since not a single real issue was spotted (aside from the usual outdated docker images randomly flaking out, etc.), IMO the change seems correct. of course this is to be confirmed by integration tests.
Issues: MEN-825
@maciejmrowiec @kjaskiewiczz @bboozzoo
> routing: changed 'integrations' URLs to 'management'

- nginx.conf
(NOTE: this PR stands on top of #41 - ignore the first commit as it's duplicated here.)
additionally to simply bringing back the change that was reverted previously, a critical issue regarding the 'login' location was fixed. see the second commit for details.
Issues: MEN-805
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
> force auth on management endpoints

- nginx.conf
We're already passing original URI. Without knowing original request's method it might not be possible to take a reasonable decision about authorization.
> nginx: embed original request method in X-Original-Method when proxying to /auth/verify

- nginx.conf
from now on, services will return relative urls in Link headers.
must be merged together with https://github.com/mendersoftware/deviceadm/pull/49
Issues: MEN-881
> config: remove Link header transformation code

- nginx.conf
mostly this:
```
nginx: add Access-Control-Allow-Origin to every 401 status response
Responses carrying 4xx codes will be blocked by CORS functionality of the
browser or requests are made to a different origin. The response is expected to
carry Access-Control-Allow-Origin header that indicates if Origin used in the
original request is allowed to access particular resource. At the javascript
side, when blocked, xhr will not contain information about request status, in
particular status code will be 0.
Use `Headers More` module to set Access-Control-Allow-Origin on every 401
response. This should not cause problems for requests that are not CORS, and
will enable CORS requests to work. The setting is applied globally in `server`
block.
``` …
> CORS again

- nginx.conf
is well supported in browsers.
Allow more ciphers; nginx uses a secure default cipherlist
(HIGH security only) and we should not require forward secrecy
only as this is expensive for an embedded device and not
that important for us (authenticity is the critical property).
This also enables use of Elliptic Curves.
Signed-off-by: Eystein Måløy Stenberg <eystein@mender.io>
> TLS 1.0 is being gradually deprecated by major websites and TLS 1.1

- entrypoint.sh
Commit bce603ac14140bdb3aea55257d18c9fae44e6418 changes the location of
certificate and private key. Entrypoint helper that checks if these are present
at specific locations was not updated though.
> entrypoint: update key/cert locations

- HACKING.md
- nginx.conf
There is no need to use proxy redirects anymore, because all services are using relative locations in location headers.
'MAPPED_PORT' is no longer used.
@bboozzoo @maciejmrowiec @mchalski
> Remove unnecessary redirects and 'MAPPED_PORT' variable from environment

- nginx.conf
Expose management endpoints, block device-only endpoints.
Enables use of:
https://github.com/mendersoftware/deviceauth/pull/109
> nginx: export management endpoints of device authentication service

- nginx.conf
Device Authentication service URLs are now aligned wit the external API URLs.
Meaning that for management API URI we can just prefix match anything that comes
in and pass it directly to the services. For device URIs, use full URIs in
`location` blocks and similarly for device token verification endpoint.
@mendersoftware/rndity @maciejmrowiec 
Goes together with https://github.com/mendersoftware/deviceauth/pull/111
> nginx: adjust proxy settings for deviceauth URL changes

- nginx.conf
Make sure that X-MEN-RequestID assigned by authentication endpoint is used for
subsequent proxy requests and logged in access log.
Signed-off-by: Maciej Borzecki <maciej.borzecki@rndity.com>
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
> nginx: log and pass X-MEN-RequestID

- entrypoint.sh
- nginx.conf
Issues: https://tracker.mender.io/browse/MEN-1262
done via a standard technique of whitelisting known hostnames, and denying all requests which don't have a Host header, or the header points to an unknown host.
the whitelist is parametrized via a template variable + env var, so that it can be configured from compose files.
this needs:
https://github.com/mendersoftware/integration/pull/287
for int tests to pass
> prevent host header injection

- Dockerfile
- entrypoint.sh
- reload-when-hosts-changed
since the 'resolver' approach didn't work, this is a workaround.
a standalone 'reload' script is introduced which periodically gets
dns names of known services. if changes are detected compared to a
previous run, '-s reload' is sent to openresty.
Issues: MEN-1227
Changelog: gateway dns cache reloading for improved recovery from service restarts
@maciejmrowiec @mendersoftware/rndity 
also, see https://tracker.mender.io/browse/MEN-1227?focusedCommentId=81746&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-81746
> reload: a dns monitor for periodic cache reloading

- nginx.conf
@mendersoftware/rndity @GregorioDiStefano 
Today we are not able to poiunt out overall request service time. Adding to the log output.
> Changelog: Include request time in gateway access logs.

- Dockerfile
- entrypoint.sh
- nginx.conf
Add X-Cache-Status header for cached content.
Cache up to 100MB of content on disk.
Enable cache revalidation with origin server.
Serve stale cache when refreshing cache or experienceing origin server issues (additional fault tollerance).
Enable browser caching for /ui, configurable by CACHE_UI env. Default: disabled.
@mendersoftware/rndity 
UI is all static content.
> Changelog: Introuduce static content caching for /ui routing.

- nginx.conf
User Administration service had its URLs aligned with API documentation. Update
nginx config to match new URL mapping.
@mendersoftware/rndity
> nginx: align gateway URLs with useradm API

- nginx.conf
in preparation for actually enforcing mgmt vs internal apis
changelog: none
goes with https://github.com/mendersoftware/deviceadm/pull/110
> nginx.conf: 1:1 routing for deviceadm

- entrypoint.sh
- nginx.conf
Introduce settings to configure and enable caching:
CACHE_UI_BROWSER_PERIOD - browser side cache persiod (1h, 1m ...)
CACHE_UI_SUCCESS_PERIOD - http 200 301 302 reponse cache time on gateway
CACHE_UI_BROWSER_PERIOD - other http statues reponse cache time on gateway
> Disable gateway caching by default. 

- entrypoint.sh
- nginx.conf
Issues: https://tracker.mender.io/browse/MEN-1718
From now on it is possible to set rate limit per IP address
for the API using environment variables.
There are two variables:
RATE_LIMIT_GLOBAL_RATE=limit - number of request per second
RATE_LIMIT_GLOBAL_BURST=burst - burst parameter defines
how many requests a client can make in excess
of the rate specified by the limit.Signed-off-by: Krzysztof Jaskiewicz <krzysiekjaskiewicz@gmail.com>
Both parameters, limit and burst, should be numbers.
@maciejmrowiec @GregorioDiStefano @mchalski
> introduce rate limits

- entrypoint.sh
- nginx.conf
nginx.conf: replace default rate limit response HTTP 503 (Service Temporarily Unavailable) with HTTP 429 (Too Many Requests)
When a client exceeds its rate limit gateway returns 429 (Too
Many Reqests) instead of 503 (Service Temporarily Unavailable)
Issue: https://tracker.mender.io/browse/MEN-1765
@maciejmrowiec @GregorioDiStefano @mchalski
> nginx.conf adjust response code

- nginx.conf
temporary, because of:
https://tracker.mender.io/browse/MEN-2386
will be researched in:
https://tracker.mender.io/browse/MEN-2407
changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
> nginx.conf: disable http2

- entrypoint.sh
- nginx.conf
make it possible to set different max-age for different envs.
demo will have 0, production (default, embedded config) will remain with 2yrs
https://tracker.mender.io/browse/MEN-2440
> add HTTP Strict Transport Security max-age setting

- nginx.conf
Adding ssl_trusted_certificate for the OCSP validation to work.
. full description: https://tracker.mender.io/browse/MC-301
ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>
> MC-301 ssl_trusted_certificate added.

- tenantadm.nginx.conf
tenantadm.conf: order of uri pattern matching matters, reorder stanzas
to avoid JWT token check request masking the public signup end-point.
> POST to /api/management/v*/tenantadm/tenants is unauthenticated

- common.nginx.conf
Restricts the ability to deploy to groups defined via RBAC.
* fills `X-MEN-RBAC-Deployments-Groups` header passed from [/verify/auth](https://github.com/mendersoftware/useradm-enterprise/pull/44/commits/b7275a3fc00205b728eb2874403148c0dddbb821#diff-58dcce776af1c084ee139709c64207cbR169)
* the headers are used in [deployments](https://github.com/mendersoftware/deployments-enterprise/pull/93/commits/90d3b703e4a236eb7bd6a18b295f97850f914f30#diff-b96384965a3a7dfb6a3d0a58346afefbR507)
* fills `X-MEN-RBAC-Inventory-Groups` for use in inventory upcoming restrictions on accessing devices
Design:
* [RBAC_deploy_to_group](https://docs.google.com/document/d/14nJGvnGJ8lXGvdX9hooHkZen4DChHP0nPFva3Uz6mws/edit?usp=sharing)
Related ticket:
* [MEN-3240](https://tracker.mender.io/browse/MEN-3240)
Related …
> MEN-3240 RBAC: per device group restrictions support

- common.nginx.conf
To enable URI/method-specific token verification features (e.g., throttling
or plan limitations), we add the X-Original-URI and X-Original-Method
headers in the token verification request used by auth_request.
> Set X-Original-URI and X-Original-Method in /devauth

- common.nginx.conf
Necessary for mendersoftware/useradm-enterprise#89
> MEN-3619: Forward host on oauth endpoints

- common.nginx.conf
- tenantadm.nginx.conf
Management endpoints can return 429 Too Many Requests when
throttling is enabled.
Nginx will translate them to 500 unfortunately; as a compromise,
translate all 500s to 429s, this way the client will
be able to see any 429s.
> config: handle 429 Too Many Requests

- common.nginx.conf
- entrypoint.sh
The http origin already gets checked by nginx with the `server_name` parameter in `non-ssl.nginx.conf` or `ssl.nginx.conf`.
The Problem is that if you set the ALLOWED_HOSTS variable to `_` which means wildcard for the nginx Server name, the origin check fails because the Regex is not valid anymore.
Signed-off-by: Felix Breuer <f.breuer94@gmail.com>
> Allow Wildcard Servername '_'

- common.nginx.conf
- entrypoint.sh
If ALLOWED_ORIGIN_HOSTS is set to "_", the Origin header is not checked.
Changelog: title
> MEN-4118: restore ALLOWED_ORIGIN_HOSTS regex match when checking Origin
