- nginx.conf
> update deployments update route

- nginx.conf
Part of the MEN-847 issue
@bboozzoo @maciejmrowiec @mchalski
> Nginx config: 'images' renamed as 'artifacts'. Ready for review; do not merge (should be merged at the same time with other parts of MEN-847 task) 

- Dockerfile
- entrypoint.sh
Use a custom entrypoint that performs addition checks before starting openresty.
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
> custom entrypoint

- nginx.conf
this causes CORS preflight request errors
> config: try to disable user authentication on OPTIONS requests

- nginx.conf
Must be merged with https://github.com/mendersoftware/integration/pull/136
> standarize key and cert name

- nginx.conf
> MEN-963 & MEN-970 Versioning + Routing

- nginx.conf
> nginx: redirect plain http requests to https port to https scheme

- .travis.yml
> Remove auto tagging docker with latest on master builds.

- .travis.yml
Checks that sign-off and changelog tags are present.
Signed-off-by: Kristian Amlie <kristian.amlie@mender.io>
> Add verification of commits.

- nginx.conf
Issue: https://tracker.mender.io/browse/MEN-1287
> nginx.conf: validate Origin header if present

- LICENSE
Changelog: None
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Update copyright to Northern.tech and current year.

- nginx.conf
https://tracker.mender.io/browse/MEN-1316
@maciejmrowiec @michaelatmender @mendersoftware/rndity
> nginx.conf: additional headers for better application security

- .travis.yml
> Fix docker tagging in push.

- Dockerfile
- entrypoint.sh
- nginx.conf
- tenantadm.nginx.conf
Issues: https://tracker.mender.io/browse/MEN-1370
Also needs https://github.com/mendersoftware/integration/pull/347
@maciejmrowiec @mendersoftware/rndity
> expose tenantadm's GET /user/tenant

- nginx.conf
Issues: https://tracker.mender.io/browse/MEN-1543
Needs: https://github.com/mendersoftware/deployments/pull/295
Parametrized int tests pass here: https://mender-jenkins.mender.io/job/mender-builder/3134/
@maciejmrowiec @mendersoftware/rndity
> nginx.config: unified routes for deployments

- entrypoint.sh
- reload-when-hosts-changed
> reload gateway when mender-gui availability changes

- .travis.yml
@GregorioDiStefano @maciejmrowiec @mchalski
> travis: remove deprecated --email flag from 'docker login'

- nginx.conf
Issues: https://tracker.mender.io/browse/MEN-1957
> nginx conf: redirect /api/management/v1/admission calls to devicauth service

- nginx.conf
Issues: https://tracker.mender.io/browse/MEN-1264
> nginx.conf: fix redirection from / to /ui/

- entrypoint.sh
- nginx.conf
Issues: https://tracker.mender.io/browse/MEN-1728
> remove deviceadm service

- entrypoint.sh
- nginx.conf
Signed-off-by: Oleksandr Miliukov <oleksandr.miliukov@northern.tech>
Changelog: Title
> nginx access log format changed to json

- nginx.conf
Issues: https://tracker.mender.io/browse/MEN-2445, https://tracker.mender.io/browse/MC-676
> nginx.conf: remove admission API location

- nginx.conf
https://tracker.mender.io/browse/MEN-2523
the main PR https://github.com/mendersoftware/inventory/pull/137 is on a feature branch, however - this one is to `master`. it shouldn't hurt, and I want to avoid the hassle of multiple feature branchesif possible.
> nginx.conf: unified route for inventory mgmt api v2

- .gitlab-ci.yml
Cherry picking #112 into 2.1.x
> Recreate CI Pipeline using templates (aka fix dind issue)

- tenantadm.nginx.conf
Changelog: None
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
> nginx.conf: made newer versions of the tenantadm api reachable

- common.nginx.conf
ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>
> Increased timeouts to handle longer requests processing.

- tenantadm.nginx.conf
Merge the two nginx stanzas to manage all the allowed methods.
> Expose the DELETE end-points to remove inactive tenants

- common.nginx.conf
> MEN-3539: Increase max body size for server-side artifact generation ep

- common.nginx.conf
https://tracker.mender.io/browse/MEN-3548
supports: https://github.com/mendersoftware/deviceauth/pull/349
combined pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/153338725
> handle deviceauth's throttling (http 429 codes)

- common.nginx.conf
> Add nginx redirection from /signup to /ui/#/signup

- common.nginx.conf
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>
> Backported request timeouts

- common.nginx.conf
> MEN-3544, MEN-3546: expose password-reset end-points without auth

- common.nginx.conf
> MEN-3933: 401 and 403 json error responses in auth verification end-points

- Dockerfile
- auditlogs.nginx.conf
- entrypoint.sh
discovered during https://tracker.mender.io/browse/MEN-3815.
(auditlogs was inaccessible via the gateway - no user POST/GET possible).
needs
https://github.com/mendersoftware/integration/pull/1012
https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/192821795
> common: expose auditlogs

- common.nginx.conf
> MEN-3953: expose the management end-point to verify the user's plan

- Dockerfile
- common.nginx.conf
- deviceconnect.nginx.conf
- entrypoint.sh
> Move deviceconnect nginx configuration to an optional conf file

- deviceconnect.nginx.conf
> Fix auth request URL for deviceconnect management API calls

- deviceconnect.nginx.conf
> MEN-4087: add authorization and RBAC support to deviceconnect

- common.nginx.conf
- entrypoint.sh
> MEN-4118: restore ALLOWED_ORIGIN_HOSTS regex match when checking Origin
